//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Healer.rc で使用
//
#define IDD_DIALOG                      101
#define IDI_ICON                        102
#define IDD_LOG                         104
#define IDR_MENU_DIALOG                 107
#define IDD_FOLLOW                      109
#define IDD_RESERVED                    111
#define IDD_SETTING                     116
#define IDD_TARGET                      118
#define IDD_COMBAT                      121
#define IDD_FELLOW                      123
#define IDD_SETTING_THRESHOLD           125
#define IDD_SETTING_TIME                127
#define IDD_SETTING_OPEN                132
#define IDD_SETTING_OTHER               134
#define IDD_SETTING_OFFSET              136
#define IDC_BUTTON_COMBAT_LIST          1000
#define IDC_COMBO_DEFAULT_PRIORITY      1000
#define IDC_COMBO_FNAME                 1000
#define IDC_EDIT_TARGET_HPP             1000
#define IDC_RADIO_FELLOW_WS_NOTUSE      1000
#define IDC_COMBO_FDISTANCE             1001
#define IDC_COMBO_FELLOW_MASTER_NAME    1001
#define IDC_EDIT_COMBAT_AREA            1001
#define IDC_GROUP_TARGET                1001
#define IDC_LIST_PC                     1001
#define IDC_SLIDER_STOP_TIME            1001
#define IDC_TAB_SETTING                 1001
#define IDC_CHECKBOX_OFFSET             1002
#define IDC_COMBO_PID                   1002
#define IDC_EDIT_COMBAT_YM              1002
#define IDC_EDIT_TARGET_NAME            1002
#define IDC_LIST_LOG_PARTY              1002
#define IDC_STATIC_STOP_TIME            1002
#define IDC_BUTTON_START                1003
#define IDC_CHECKBOX_CASTING            1003
#define IDC_CHECKBOX_SAVE_POSITION      1003
#define IDC_EDIT_COMBAT_X               1003
#define IDC_EDIT_TARGET_DISTANCE        1003
#define IDC_LIST_LOG_LINKSHELL          1003
#define IDC_RADIO_FELLOW_UP             1003
#define IDC_BUTTON_COMBAT_START         1004
#define IDC_CHECKBOX_LOCKON             1004
#define IDC_COMBO_JOB                   1004
#define IDC_EDIT_OFFSET_ACTIVITY_INFO   1004
#define IDC_RADIO_FELLOW_DOWN           1004
#define IDC_SLIDER_DELTA_HPP1           1004
#define IDC_BUTTON_TARGET_ADD           1005
#define IDC_COMBO_PRIORITY              1005
#define IDC_EDIT_FELLOW_WS              1005
#define IDC_EDIT_STOPWAV                1005
#define IDC_LIST_COMBAT                 1005
#define IDC_SLIDER_SPELL_DISTANCE       1005
#define IDC_BUTTON_DONE                 1006
#define IDC_CHECKBOX_AREASTOP           1006
#define IDC_CHECKBOX_FELLOW_CAST        1006
#define IDC_EDIT_OFFSET_NPCLIST         1006
#define IDC_EDIT_TARGET_CHANGEDID       1006
#define IDC_LIST_LOG                    1006
#define IDC_CHECKBOX_WINDOWERHELPER     1007
#define IDC_COMBO_RESERVED_CHARNAME     1007
#define IDC_EDIT_COMBAT_YM_SEARCH       1007
#define IDC_EDIT_FELLOW_HPP             1007
#define IDC_BUTTON_COMBAT_CAMP          1008
#define IDC_BUTTON_OPEN_STOPWAV         1008
#define IDC_COMBO_RESERVED_CHARHP       1008
#define IDC_EDIT_OFFSET_TARGET          1008
#define IDC_EDIT_TARGET_FIXEDID         1008
#define IDC_STATIC_SPELL_DISTANCE       1008
#define IDC_BUTTON_RESERVED_ADD         1009
#define IDC_BUTTON_SAVE                 1009
#define IDC_EDIT_COMBAT_Y               1009
#define IDC_EDIT_DEFAULT_PIDNAME        1009
#define IDC_RADIO_FELLOW_WS_FIRST       1009
#define IDC_EDIT_COMBAT_Z               1010
#define IDC_EDIT_OFFSET_VIEWSTYLE       1010
#define IDC_RADIO_FELLOW_WS_USE         1010
#define IDC_SLIDER_MOVE_WAIT_TIME       1010
#define IDC_BUTTON_TARGET_LINK1         1011
#define IDC_CHECKBOX_FELLOW_LINK        1011
#define IDC_EDIT_COMBAT_WAIT_TIME       1011
#define IDC_LIST_RESERVED               1011
#define IDC_STATIC_MOVE_WAIT_TIME       1011
#define IDC_BUTTON_TARGET_LINK2         1012
#define IDC_CHECKBOX_TARGET_DEFAULTOPEN 1012
#define IDC_EDIT_OFFSET_CAST            1012
#define IDC_RADIO_FELLOW_WS_NEXT        1012
#define IDC_BUTTON_TARGET_LINK3         1013
#define IDC_CHECKBOX_TARGET_DEFAULTOPEN_LINKGROUP 1013
#define IDC_EDIT_COMBAT_WS              1013
#define IDC_BUTTON_FELLOW_START         1014
#define IDC_BUTTON_TARGET_LINK4         1014
#define IDC_CHECKBOX_TARGET_DEFAULTOPEN_ADD 1014
#define IDC_EDIT_COMBAT_NMID            1014
#define IDC_EDIT_OFFSET_RECAST          1014
#define IDC_CHECKBOX_LOG_DEFAULTOPEN    1015
#define IDC_RADIO_COMBAT_UP             1015
#define IDC_BUTTON_TARGET_LINK_OPEN     1016
#define IDC_CHECKBOX_COMBAT_NMID        1016
#define IDC_CHECKBOX_HINSHI_DELTAHP     1016
#define IDC_EDIT_OFFSET_NOWSTA          1016
#define IDC_SLIDER_AREA_WAIT_TIME       1017
#define IDC_EDIT_OFFSET_MAP             1018
#define IDC_RADIO_COMBAT_DOWN           1018
#define IDC_STATIC_AREA_WAIT_TIME       1018
#define IDC_EDIT_DEFAULT_FOLLOWER       1019
#define IDC_EDIT_COMBAT_HPP             1020
#define IDC_EDIT_OFFSET_NPCMAP          1020
#define IDC_STATIC_DELTA_HPP1           1020
#define IDC_STATIC_DELTA_HPP2           1021
#define IDC_SLIDER_DELTA_HPP2           1022
#define IDC_CHECKBOX_COMBAT_WS          1023
#define IDC_STATIC_DELTA_HPP3           1023
#define IDC_SLIDER_DELTA_HPP3           1024
#define IDC_STATIC_DELTA_HPP4           1025
#define IDC_SLIDER_DELTA_HPP4           1026
#define IDC_STATIC_DELTA_HPP5           1027
#define IDC_SLIDER_DELTA_HPP5           1028
#define IDC_BUTTON_FSTART               1030
#define IDC_BUTTON_RESERVED_START       1031
#define IDC_SLIDER_CMD_INTERVAL         1032
#define IDC_STATIC_CMD_INTERVAL         1033
#define IDC_SLIDER_CAST_WAIT_TIME       1034
#define IDC_SLIDER_CMD_WAIT_TIME        1035
#define IDC_STATIC_CAST_WAIT_TIME       1036
#define IDC_STATIC_CMD_WAIT_TIME        1037
#define IDC_CHECKBOX_FOLLOW_DEFAULTOPEN 1038
#define IDC_CHECKBOX_RESERVED_DEFAULTOPEN 1039
#define IDC_STATIC_CURE_WAIT_TIME       1040
#define IDC_SLIDER_CURE_WAIT_TIME       1041
#define IDM_LOG_OPEN                    40000
#define IDM_END                         40001
#define IDM_FOLLOW_OPEN                 40002
#define IDM_RESERVED_OPEN               40003
#define IDM_SETTING_OPEN                40004
#define IDM_VERSION                     40005
#define IDM_CHANGE_MAXHP                40006
#define IDM_DELETE_CHAR                 40007
#define IDM_TARGET_OPEN                 40008
#define IDM_EDIT_HEALER_INI             40009
#define IDM_EDIT_CHARACTER_INI          40010
#define IDM_COMBAT_OPEN                 40011
#define IDM_FELLOW_OPEN                 40012
#define IDM_LOG_ALL                     40019
#define IDM_LOG_PARTY                   40020
#define IDM_LOG_LINKSHELL               40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
